site_name: Enma Dev
site_url: https://enma.dev
site_author: Prashant Dwivedi
site_description: >-
  An enma.dev, a simple Linux tips and tricks website, shares that experience with linux exploration.

# Copyright
copyright: Copyright &copy; 2022 Prashant Dwivedi

# Configuration
extra_css:
  - assets/stylesheets/extra.css

#theme
theme:
  logo: assets/enma-logo.svg
  favicon: assets/enma-logo.svg

  #features
  features:
    #- announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    #- header.autohide
    #- navigation.expand
    - navigation.indexes
    - navigation.instant
    #- navigation.prune
    - navigation.sections
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    #- toc.integrate
  
  #theme-name-and-basic-color
  name: material
  palette:
      # Palette toggle for dark mode
    - scheme: slate
      primary: teal
    
  
  #fonts
  font:
    text: Roboto
    code: Roboto Mono
  
  #icons
  icon:
    logo: logo

#extenstions
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      auto_title: true
      linenums: true
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem
  - pymdownx.smartsymbols
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - abbr
  - attr_list
  - def_list
  - tables
  - footnotes
  - md_in_html

#plugins
plugins:
  - glightbox
  - search

#footer
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leodwivedi

#nav-page tree
nav:
  - Home: index.md
  #- Linux Commands:
  - Linux Software:
    - Uptime kuma: linux-software/Uptime-kuma-setup.md
    - Local error: linux-software/how-to-fix-a-local-setting-warning-from-perl.md
  #- Tools Customise: