site_name: Enma Dev
site_url: https://enma.dev
site_author: Prashant Dwivedi
site_description: >-
  An enma.dev, a simple Linux tips and tricks website, shares that experience with linux exploration.

# Configuration
extra_css:
  - assets/stylesheets/extra.css

#theme
theme:
  logo: assets/enma-dev-logo.svg
  favicon: assets/enma-dev-logo.svg

  #features
  features:
    #- announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    #- header.autohide
    #- navigation.expand
    - navigation.indexes
    - navigation.instant
    #- navigation.prune
    - navigation.sections
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    #- toc.integrate
  
  #theme-name-and-basic-color
  name: material
  palette:
  # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  #fonts
  font:
    text: Roboto
    code: Roboto Mono
  
  #icons
  icon:
    logo: logo

#extenstions
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      auto_title: false
      linenums: true
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem
  - pymdownx.smartsymbols
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - abbr
  - attr_list
  - def_list
  - tables
  - footnotes
  - md_in_html

#plugins
plugins:
  - glightbox
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

#footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prashantdwivedi/enma

#nav-page tree
nav:
  - Home: index.md
  #- Linux Commands:
  - Linux Software:
    - Uptime Kuma Install: linux-software/uptime-kuma-install.md
    - Adguard Home Install: linux-software/adguard-home-install.md
    - Pi-hole Install: linux-software/pihole-install.md
  - Tools Customise:
    - Change hostname: tools-customise/change-hostname.md
    - Create and remove swap files: tools-customise/create-and-remove-swap-files.md
    - Overclocking Pi Zero 2W: tools-customise/overclocking-pi-zero-2w.md